# Generated by Django 5.2.6 on 2025-10-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_processing', '0002_alter_artwork_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='cloudinary_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL if saved to gallery', max_length=500),
        ),
    ]
