# Generated by Django 5.2.6 on 2025-10-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_bio',
            field=models.TextField(blank=True, help_text='AI-generated artist bio based on artwork analysis', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_bio_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the AI bio was last generated', null=True),
        ),
    ]
