# Generated by Django 5.2.6 on 2025-10-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_ai_bio_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='artist_personality',
            field=models.TextField(blank=True, help_text='AI-generated artist personality type and description', max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artist_personality_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the artist personality was last generated', null=True),
        ),
    ]
