# Generated by Django 5.2.6 on 2025-10-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_artist_personality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skill_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='AI-analyzed skill metrics: composition, color_theory, creativity, complexity, technical_skill with scores and growth'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill_analysis_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the skill analysis was last updated', null=True),
        ),
    ]
